[versions]

# Version
compileSdk = "36"
minSdk = "28"
targetSdk = "35"
versionCode = "3"
versionName = "1.0.2"

# Kotlin
agp = "8.9.2"
kotlin = "2.0.21"
kotlinParcelize = "1.8.20"
kotlinxCollectionsImmutable = "0.3.5"

# AndroidX
coreKtx = "1.16.0"
appcompat = "1.7.1"
material = "1.13.0"
material3 = "1.4.0"
lifecycle = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.01"
navigationCompose = "2.9.5"
browser="1.9.0"

# Test
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
uiTest = "1.9.4"

# Network
okhttpBom = "4.12.0"
retrofit = "2.11.0"
serialization = "1.6.3"

# Hilt
hilt = "2.57.2"
hiltCompiler = "2.57.2"
hiltNavigationCompose = "1.3.0"

# Coil
coil = "2.7.0"

# Timber
timber = "5.0.1"

# Third Party
ksp = "2.0.21-1.0.25"

# Lottie
lottie = "6.7.0"

ktlint = "13.1.0"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlinParcelize" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[libraries]
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser"}

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "uiTest" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "uiTest" }

# Network
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttpBom" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version = "0.8.0" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltCompiler" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }


# Coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# Timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }


[bundles]
androidx = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "material",
    "material3",
    "androidx-lifecycle-runtime",
    "androidx-lifecycle-viewmodel",
    "androidx-activity-compose",
    "androidx-navigation-compose"
]

test = [
    "androidx-ui-test-junit",
    "androidx-ui-test-manifest",
    "androidx-junit",
    "androidx-espresso-core"
]

debug = [
    "androidx-ui-test-manifest"
]

okhttp = [
    "okhttp",
    "logging-interceptor"
]

retrofit = [
    "retrofit",
    "retrofit-serialization"
]

hilt = [
    "hilt-android",
    "androidx-hilt-navigation-compose"
]
